apiVersion: v1
kind: Service
metadata:
  labels:
    service: k8s-demo-svc
  name: k8s-demo-svc
spec:
  type: NodePort
  ports:
    - name: "springboot"
      port: 5400
      targetPort: 5400
  selector:
    app: k8s-demo-app